version: "3.8"

services:
  site-dev:
    build:
      context: ./docker
      dockerfile: Dockerfile.docs
    tty: true
    working_dir: /docs
    volumes:
      - ./docs:/docs

  drg:
    build:
      context: .
      dockerfile: docker/Dockerfile.drg
    volumes:
      - ./src/ros_msgs:/home/docker/catkin_ws/src/ros_msgs
      - ./src/pp_env_model:/home/docker/catkin_ws/src/pp_env_model
    depends_on:
      - rosmaster

  rosmaster:
     image: ros:noetic
     command: "roscore"
     environment:
       - ROS_HOSTNAME=rosmaster


  
